name: crud_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flushbar: ^1.10.4
  auto_size_text: ^2.1.0
  sqflite: ^1.3.0
  flutter_svg: ^0.19.2+1
  flutter_typeahead: ^2.0.0
  pdf: ^2.0.0
  flutter_pdfview: ^1.0.4
  path_provider: ^1.6.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1


flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon_backgroud.png"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/vinhos.csv
    - assets/gifs/loading.gif
    - assets/images/wine_background.svg
    - assets/images/botton_image.svg
    - assets/images/bandeiras/albania.png
    - assets/images/bandeiras/alemanha.png
    - assets/images/bandeiras/argentina.png
    - assets/images/bandeiras/australia.png
    - assets/images/bandeiras/australia.png
    - assets/images/bandeiras/austria.png
    - assets/images/bandeiras/azerbaijao.png
    - assets/images/bandeiras/belgica.png
    - assets/images/bandeiras/bielorussia.png
    - assets/images/bandeiras/bolivia.png
    - assets/images/bandeiras/brasil.png
    - assets/images/bandeiras/bulgaria.png
    - assets/images/bandeiras/canada.png
    - assets/images/bandeiras/cazaquistao.png
    - assets/images/bandeiras/chile.png
    - assets/images/bandeiras/china.png
    - assets/images/bandeiras/colombia.png
    - assets/images/bandeiras/costaRica.png
    - assets/images/bandeiras/croacia.png
    - assets/images/bandeiras/cuba.png
    - assets/images/bandeiras/dinamarca.png
    - assets/images/bandeiras/equador.png
    - assets/images/bandeiras/dinamarca.png
    - assets/images/bandeiras/equador.png
    - assets/images/bandeiras/eslovaquia.png
    - assets/images/bandeiras/espanha.png
    - assets/images/bandeiras/estadosUnidos.png
    - assets/images/bandeiras/finlandia.png
    - assets/images/bandeiras/franca.png
    - assets/images/bandeiras/grecia.png
    - assets/images/bandeiras/guatemala.png
    - assets/images/bandeiras/guiana.png
    - assets/images/bandeiras/haiti.png
    - assets/images/bandeiras/holanda.png
    - assets/images/bandeiras/honduras.png
    - assets/images/bandeiras/hungria.png
    - assets/images/bandeiras/irlanda.png
    - assets/images/bandeiras/islandia.png
    - assets/images/bandeiras/italia.png
    - assets/images/bandeiras/jamaica.png
    - assets/images/bandeiras/japao.png
    - assets/images/bandeiras/lituania.png
    - assets/images/bandeiras/mexico.png
    - assets/images/bandeiras/noruega.png
    - assets/images/bandeiras/panama.png
    - assets/images/bandeiras/paraguai.png
    - assets/images/bandeiras/peru.png
    - assets/images/bandeiras/polonia.png
    - assets/images/bandeiras/portugal.png
    - assets/images/bandeiras/reinoUnido.png
    - assets/images/bandeiras/republicaDominicana.png
    - assets/images/bandeiras/romenia.png
    - assets/images/bandeiras/russia.png
    - assets/images/bandeiras/suecia.png
    - assets/images/bandeiras/suica.png
    - assets/images/bandeiras/turquia.png
    - assets/images/bandeiras/ucrania.png
    - assets/images/bandeiras/uruguai.png
    - assets/images/bandeiras/venezuela.png
    - assets/images/backGrounds/albania.png
    - assets/images/backGrounds/alemanha.png
    - assets/images/backGrounds/argentina.png
    - assets/images/backGrounds/australia.png
    - assets/images/backGrounds/australia.png
    - assets/images/backGrounds/austria.png
    - assets/images/backGrounds/azerbaijao.png
    - assets/images/backGrounds/belgica.png
    - assets/images/backGrounds/bielorussia.png
    - assets/images/backGrounds/bolivia.png
    - assets/images/backGrounds/brasil.png
    - assets/images/backGrounds/bulgaria.png
    - assets/images/backGrounds/canada.png
    - assets/images/backGrounds/cazaquistao.png
    - assets/images/backGrounds/chile.png
    - assets/images/backGrounds/china.png
    - assets/images/backGrounds/colombia.png
    - assets/images/backGrounds/costaRica.png
    - assets/images/backGrounds/croacia.png
    - assets/images/backGrounds/cuba.png
    - assets/images/backGrounds/dinamarca.png
    - assets/images/backGrounds/equador.png
    - assets/images/backGrounds/dinamarca.png
    - assets/images/backGrounds/equador.png
    - assets/images/backGrounds/eslovaquia.png
    - assets/images/backGrounds/espanha.png
    - assets/images/backGrounds/estadosUnidos.png
    - assets/images/backGrounds/finlandia.png
    - assets/images/backGrounds/franca.png
    - assets/images/backGrounds/grecia.png
    - assets/images/backGrounds/guatemala.png
    - assets/images/backGrounds/guiana.png
    - assets/images/backGrounds/haiti.png
    - assets/images/backGrounds/holanda.png
    - assets/images/backGrounds/honduras.png
    - assets/images/backGrounds/hungria.png
    - assets/images/backGrounds/irlanda.png
    - assets/images/backGrounds/islandia.png
    - assets/images/backGrounds/italia.png
    - assets/images/backGrounds/jamaica.png
    - assets/images/backGrounds/japao.png
    - assets/images/backGrounds/lituania.png
    - assets/images/backGrounds/mexico.png
    - assets/images/backGrounds/noruega.png
    - assets/images/backGrounds/panama.png
    - assets/images/backGrounds/paraguai.png
    - assets/images/backGrounds/peru.png
    - assets/images/backGrounds/polonia.png
    - assets/images/backGrounds/portugal.png
    - assets/images/backGrounds/reinoUnido.png
    - assets/images/backGrounds/republicaDominicana.png
    - assets/images/backGrounds/romenia.png
    - assets/images/backGrounds/russia.png
    - assets/images/backGrounds/suecia.png
    - assets/images/backGrounds/suica.png
    - assets/images/backGrounds/turquia.png
    - assets/images/backGrounds/ucrania.png
    - assets/images/backGrounds/uruguai.png
    - assets/images/backGrounds/venezuela.png
  fonts:
    - family: GreatVibes
      fonts:
      - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
